preferred_syntax = :sass
http_path = '/'
css_dir = 'assets/css'
sass_dir = 'sass'
images_dir = 'assets/picts'
javascripts_dir = 'assets/javascripts'
relative_assets = true
line_comments = true
# output_style = :compressed
